const { PrismaClient } = require("@prisma/client");
const db = new PrismaClient();

const PRODUCTS = [
  {
    slug: "national-home-kit",
    name: "National Home Kit",
    team: "Maldives National Team",
    collection: "National Team",
    league: "International",
    mode: "instant",
    price: 780,
    gradientFrom: "#0E2438",
    gradientTo: "#17A398",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "S,M,L,XL",
    description:
      "The official Maldives National Team home shirt. Breathable fan-version fabric or match-grade AeroDry — same crest, same colours, made for the terraces or the five-a-side pitch.",
    featured: true,
  },
  {
    slug: "red-snappers-away-kit",
    name: "Red Snappers Away Kit",
    team: "U20 Football Team",
    collection: "National Team",
    league: "U20 International",
    mode: "instant",
    price: 420,
    gradientFrom: "#F2703C",
    gradientTo: "#C8383A",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "S,M,L",
    description: "The away kit for the U20s — Red Snappers colours in a lightweight fan cut.",
    featured: true,
  },
  {
    slug: "beyru-kulabu-classic",
    name: "Beyru Kulabu Classic",
    team: "Club Kit",
    collection: "Club Kits",
    league: "Domestic League",
    mode: "preorder",
    price: 450,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#17A398",
    gradientTo: "#0E2438",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "M,L,XL",
    description: "Classic club colours in Pro Interlock fabric. Made to order by our supplier.",
  },
  {
    slug: "world-cup-fever-kit",
    name: "World Cup Fever Kit",
    team: "Dhivehi Edition",
    collection: "National Team",
    league: "International",
    mode: "preorder",
    price: 380,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#F2703C",
    gradientTo: "#17A398",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "S,M,L,XL",
    description: "Limited World Cup season print in a Dhivehi-inspired colourway.",
  },
  {
    slug: "gfc25-referee-set",
    name: "GFC25 Referee Set",
    team: "Official Match Kit",
    collection: "Match Officials",
    league: "Official",
    mode: "instant",
    price: 390,
    gradientFrom: "#0E2438",
    gradientTo: "#F2703C",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "S,M,L,XL",
    description: "The full referee kit — shirt, shorts and socks in regulation colours.",
  },
  {
    slug: "hiri-club-jersey",
    name: "Hiri Club Jersey",
    team: "Club Kit",
    collection: "Club Kits",
    league: "Domestic League",
    mode: "preorder",
    price: 410,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#C8383A",
    gradientTo: "#0E2438",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "M,L",
    description: "Hiri club jersey, made to order in your choice of Fan Version or Pro Interlock.",
  },
  {
    slug: "felayla-fc-home-kit",
    name: "Felayla FC Home Kit",
    team: "Felayla FC",
    collection: "Club Kits",
    league: "Domestic League",
    mode: "preorder",
    price: 450,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#3E7CB1",
    gradientTo: "#0E2438",
    image: "/Products/Feleyla.jpg",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "XS,S,M,L,XL,2XL,3XL",
    description:
      "Felayla FC's sky blue and royal blue home kit — sublimated crest, and custom name and squad number printing.",
    featured: true,
  },
  {
    slug: "mma-social-club-home-kit",
    name: "MMA Social Club Home Kit",
    team: "MMA Social Club",
    collection: "Club Kits",
    league: "Social League",
    mode: "preorder",
    price: 520,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#6FA8DC",
    gradientTo: "#0E2438",
    image: "/Products/MMA Home.jpg",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "XS,S,M,L,XL,2XL,3XL",
    description:
      "Full MMA Social Club home kit — jersey, shorts and socks — sky blue stripes with navy trim, name and number printing included.",
    featured: true,
  },
  {
    slug: "mma-social-club-away-kit",
    name: "MMA Social Club Away Kit",
    team: "MMA Social Club",
    collection: "Club Kits",
    league: "Social League",
    mode: "preorder",
    price: 420,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#1E7A4C",
    gradientTo: "#0E2438",
    image: "/Products/Flower Green.jpg",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "XS,S,M,L,XL,2XL,3XL",
    description:
      "MMA Social Club away kit in forest green with a subtle floral print, custom name and squad number printing.",
  },
  {
    slug: "mma-social-club-official-kit",
    name: "MMA Social Club Official Kit",
    team: "MMA Social Club",
    collection: "Match Officials",
    league: "Social League",
    mode: "preorder",
    price: 400,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#2B2F36",
    gradientTo: "#0E2438",
    image: "/Products/MMA Away.jpg",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "XS,S,M,L,XL,2XL,3XL",
    description: "Match official shirt for MMA Social Club fixtures — black pinstripe with club monogram.",
  },
  {
    slug: "mib-15th-anniversary-jersey",
    name: "MIB 15th Anniversary Jersey",
    team: "Maldives Islamic Bank",
    collection: "Corporate Apparel",
    league: "Corporate",
    mode: "preorder",
    price: 460,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#1B2A4A",
    gradientTo: "#1E7A4C",
    image: "/Products/MIB.jpg",
    materials: "Wetlook,Honeycomb,Jacquard Wave,Camouflage Jacquard Mesh,Chevron Jacquard,Checkered Eyelet Mesh",
    sizes: "XS,S,M,L,XL,2XL,3XL",
    description:
      "Commemorative jersey marking 15 years of Maldives Islamic Bank — custom name and department printing available.",
    featured: true,
  },
  {
    slug: "mib-corporate-polo",
    name: "MIB Corporate Polo",
    team: "Maldives Islamic Bank",
    collection: "Corporate Apparel",
    league: "Corporate",
    mode: "preorder",
    price: 350,
    preorderEta: "3–4 weeks to Male'",
    gradientFrom: "#14181C",
    gradientTo: "#1B2A4A",
    image: "/Products/MIB Official.jpg",
    materials: "Baby PK,Waffle,Dot Waffle,Crocodile",
    sizes: "XS,S,M,L,XL,2XL,3XL",
    description: "Embroidered corporate polo for Maldives Islamic Bank staff — role and department printing available.",
  },
  {
    slug: "shaviyani-corporate-polo",
    name: "Shaviyani Corporate Polo",
    team: "Shaviyani Pro",
    collection: "Corporate Apparel",
    league: "Corporate",
    mode: "instant",
    price: 320,
    gradientFrom: "#14181C",
    gradientTo: "#17A398",
    image: "/Products/Shaviyani Corporate T- Shirt.jpg",
    materials: "Baby PK,Waffle,Dot Waffle,Crocodile",
    sizes: "XS,S,M,L,XL,2XL,3XL",
    description: "Our own house polo — black with a teal gradient hem accent and Shaviyani wordmark.",
  },
  {
    slug: "classic-cup-trophy",
    name: "Classic Cup Trophy",
    team: "Sports Trophy",
    collection: "Trophies & Awards",
    league: "Tournament",
    mode: "preorder",
    price: 450,
    preorderEta: "1–2 weeks to Male'",
    gradientFrom: "#D9A441",
    gradientTo: "#14181C",
    materials: "Metal,Acrylic,Resin,Crystal",
    sizes: "Small (15cm),Medium (20cm),Large (30cm)",
    description:
      "Classic tiered cup trophy for tournament winners — engraved names, custom logo plate, multi-tier design.",
    featured: true,
  },
  {
    slug: "mvp-star-award",
    name: "MVP Star Award",
    team: "Sports Trophy",
    collection: "Trophies & Awards",
    league: "Individual Award",
    mode: "preorder",
    price: 320,
    preorderEta: "1–2 weeks to Male'",
    gradientFrom: "#D9A441",
    gradientTo: "#7A1F2B",
    materials: "Metal,Acrylic,Resin,Crystal",
    sizes: "Small (15cm),Medium (20cm)",
    description:
      "Star-cut individual award for MVP, top scorer or player of the match — engraved name and event details.",
  },
  {
    slug: "academic-honor-award",
    name: "Academic Honor Award",
    team: "Academic Trophy",
    collection: "Trophies & Awards",
    league: "Academic",
    mode: "preorder",
    price: 280,
    preorderEta: "1–2 weeks to Male'",
    gradientFrom: "#C7D0D9",
    gradientTo: "#14181C",
    materials: "Wood,Acrylic,Glass with Metallic Accents",
    sizes: "Small (15cm),Medium (20cm)",
    description:
      "Elegant award for scholastic achievement — laser-engraved text, customizable plaque, academic motifs.",
  },
  {
    slug: "champion-medal",
    name: "Champion Medal",
    team: "Medal",
    collection: "Trophies & Awards",
    league: "Tournament",
    mode: "preorder",
    price: 120,
    preorderEta: "1–2 weeks to Male'",
    gradientFrom: "#CD7F32",
    gradientTo: "#14181C",
    materials: "Gold Finish,Silver Finish,Bronze Finish",
    sizes: "Standard (7cm)",
    description: "Ribboned medal for champions and finalists — custom engraving and event branding.",
  },
  {
    slug: "recognition-plaque",
    name: "Recognition Plaque",
    team: "Plaque",
    collection: "Trophies & Awards",
    league: "Corporate",
    mode: "preorder",
    price: 350,
    preorderEta: "1–2 weeks to Male'",
    gradientFrom: "#8C6239",
    gradientTo: "#14181C",
    materials: "Wood,Acrylic,Metal",
    sizes: "Small (A5),Medium (A4),Large (A3)",
    description:
      "Wall-mounted or freestanding plaque for lasting recognition — full-colour printing, custom shapes, UV-resistant finish.",
  },
  {
    slug: "champions-shield",
    name: "Champions Shield",
    team: "Sports Trophy",
    collection: "Trophies & Awards",
    league: "Tournament",
    mode: "preorder",
    price: 480,
    preorderEta: "1–2 weeks to Male'",
    gradientFrom: "#D9A441",
    gradientTo: "#14181C",
    image: "/Products/Champions Scheild.jpg",
    materials: "Metal,Acrylic,Resin,Crystal",
    sizes: "Small (15cm),Medium (20cm),Large (30cm)",
    description:
      "Engraved gold shield trophy on an acrylic stand — full custom text, event date, and sponsor/council logos, built to order for tournament finals.",
    featured: true,
  },
  {
    slug: "ceremonial-crown-trophy",
    name: "Ceremonial Crown Trophy",
    team: "Custom Trophy",
    collection: "Trophies & Awards",
    league: "Ceremonial",
    mode: "preorder",
    price: 550,
    preorderEta: "1–2 weeks to Male'",
    gradientFrom: "#D9A441",
    gradientTo: "#7A1F2B",
    image: "/Products/Crown.jpg",
    materials: "Metal,Resin,Acrylic",
    sizes: "Small,Medium,Large",
    description:
      "Ornate cast crown trophy for pageants, ceremonies and top-honour awards — fine relief detail with custom engraving on the base.",
    featured: true,
  },
];

const ORDERS = [
  {
    orderNumber: "JZ-1042",
    customerName: "Ahmed Rasheed",
    customerEmail: "ahmed.rasheed@example.com",
    customerPhone: "+960 777-1234",
    address: "M. Sea Breeze, Male'",
    island: "Male'",
    productSlug: "national-home-kit",
    material: "Match Grade",
    size: "L",
    qty: 2,
    supplierCost: 340,
    shippingCost: 60,
    status: "In Transit",
    isPreorder: false,
    daysAgo: 15,
  },
  {
    orderNumber: "JZ-1043",
    customerName: "Club Valencia FC",
    customerEmail: "manager@clubvalencia.example",
    customerPhone: "+960 777-5678",
    address: "Team Office, Hulhumale'",
    island: "Hulhumale'",
    productSlug: "gfc25-referee-set",
    material: "Pro Interlock",
    size: "Team Order (12x)",
    qty: 12,
    supplierCost: 2160,
    shippingCost: 220,
    status: "Customs Clearance",
    isPreorder: true,
    daysAgo: 21,
  },
  {
    orderNumber: "JZ-1044",
    customerName: "Shaliya Moosa",
    customerEmail: "shaliya.moosa@example.com",
    customerPhone: "+960 777-9012",
    address: "G. Lily Villa, Male'",
    island: "Male'",
    productSlug: "red-snappers-away-kit",
    material: "Fan Version",
    size: "M",
    qty: 1,
    supplierCost: 165,
    shippingCost: 30,
    status: "Delivered",
    isPreorder: false,
    daysAgo: 33,
  },
  {
    orderNumber: "JZ-1045",
    customerName: "Ibrahim Munawwar",
    customerEmail: "ibrahim.m@example.com",
    customerPhone: "+960 777-3456",
    address: "H. Ocean View, Male'",
    island: "Male'",
    productSlug: "beyru-kulabu-classic",
    material: "Pro Interlock",
    size: "XL",
    qty: 1,
    supplierCost: 190,
    shippingCost: 30,
    status: "Placed",
    isPreorder: true,
    daysAgo: 4,
  },
  {
    orderNumber: "JZ-1046",
    customerName: "Hussain Faisal",
    customerEmail: "hussain.faisal@example.com",
    customerPhone: "+960 777-7890",
    address: "Ma. Coral Reef, Male'",
    island: "Male'",
    productSlug: "world-cup-fever-kit",
    material: "Match Grade",
    size: "M",
    qty: 3,
    supplierCost: 510,
    shippingCost: 75,
    status: "Sent to Supplier",
    isPreorder: true,
    daysAgo: 6,
  },
];

const ALL_STATUSES = [
  "Placed",
  "Sent to Supplier",
  "In Transit",
  "Customs Clearance",
  "Out for Delivery",
  "Delivered",
];

async function main() {
  console.log("Seeding products...");
  for (const p of PRODUCTS) {
    await db.product.upsert({
      where: { slug: p.slug },
      update: p,
      create: p,
    });
  }

  console.log("Seeding orders...");
  for (const o of ORDERS) {
    const existing = await db.order.findUnique({ where: { orderNumber: o.orderNumber } });
    if (existing) continue;

    const product = await db.product.findUnique({ where: { slug: o.productSlug } });
    const placedAt = new Date(Date.now() - o.daysAgo * 24 * 60 * 60 * 1000);
    const subtotal = product.price * o.qty;
    const statusIdx = ALL_STATUSES.indexOf(o.status);
    const reachedStatuses = ALL_STATUSES.slice(0, statusIdx + 1);

    await db.order.create({
      data: {
        orderNumber: o.orderNumber,
        customerName: o.customerName,
        customerEmail: o.customerEmail,
        customerPhone: o.customerPhone,
        address: o.address,
        island: o.island,
        subtotal,
        shippingCost: o.shippingCost,
        supplierCost: o.supplierCost,
        status: o.status,
        isPreorder: o.isPreorder,
        createdAt: placedAt,
        items: {
          create: [
            {
              productId: product.id,
              name: product.name,
              material: o.material,
              size: o.size,
              qty: o.qty,
              price: product.price,
            },
          ],
        },
        statusLogs: {
          create: reachedStatuses.map((s, i) => ({
            status: s,
            changedAt: new Date(placedAt.getTime() + i * 2 * 24 * 60 * 60 * 1000),
          })),
        },
      },
    });
  }

  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
